In [1]:
# Importing Library
import pandas as pd

In [3]:
# Load excel file 
input_file = r"C:\Users\Public\DELOITTE\data\Task 5 Equality Table.xlsx"

In [4]:
df = pd.read_excel(input_file)

In [24]:
print(df.columns.tolist())

['Factory', 'Job Role', 'Equality Score', 'Equality class']

In [6]:
df.head()

                 Factory     Job Role  Equality Score  Equality class
0  Daikibo Factory Meiyo      C-Level             -25             NaN
1  Daikibo Factory Meiyo           VP             -26             NaN
2  Daikibo Factory Meiyo     Director             -19             NaN
3  Daikibo Factory Meiyo  Sr. Manager             -15             NaN
4  Daikibo Factory Meiyo      Manager             -14             NaN

In [21]:
# Classify equality score
def equality_score(score):
    if score < -20 or score > 20:
        return "Highly Discriminative"
    elif -10 <= score <= 10:
        return "Fair"
    else:
        return "Unfair"

In [22]:
df["Equality class"] = df["Equality Score"].apply(equality_score)

In [23]:
df.head()

                 Factory     Job Role  Equality Score         Equality class
0  Daikibo Factory Meiyo      C-Level             -25  Highly Discriminative
1  Daikibo Factory Meiyo           VP             -26  Highly Discriminative
2  Daikibo Factory Meiyo     Director             -19                 Unfair
3  Daikibo Factory Meiyo  Sr. Manager             -15                 Unfair
4  Daikibo Factory Meiyo      Manager             -14                 Unfair

In [25]:
df.to_excel("output_task_2_.xlsx", index=False)

In [26]:
print('File Saved!!')

File Saved!!